steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
  # Paso para la notificación a Slack
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -X POST -H 'Content-type: application/json' --data '{"text": "El despliegue del servicio $_SERVICE_NAME (commit: $COMMIT_SHA) en Cloud Run ha sido completado en $_DEPLOY_REGION ✅"}' "$SLACK_WEBHOOK_URL"
    env:
      - 'SLACK_WEBHOOK_URL'

availableSecrets:
  secretManager:
    - versionName: "projects/565898129046/secrets/SLACK_WEBHOOK_URL/versions/1"
      env: "SLACK_WEBHOOK_URL"

images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: backend-365app
  _DEPLOY_REGION: europe-west1
  _TRIGGER_ID: 1ee26914-7778-4edc-b9b3-a127077196ed
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - backend-365app
