-- AlterTable
ALTER TABLE "ParesFichaje" ADD COLUMN     "horasAprendiz" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "horasCoordinacion" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "horasExtras" DOUBLE PRECISION NOT NULL DEFAULT 0;
