name: Build and Push silema Image to Google Cloud Platform
on:
  push:
    branches: [ master ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: silema
      PROJECT_ID: silema
      REGION: europe-west1
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY  }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v major
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest $REGION-docker.pkg.dev/$PROJECT_ID/silema-repo/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest $REGION-docker.pkg.dev/$PROJECT_ID/silema-repo/$IMAGE_NAME:$GIT_TAG
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/silema-repo/$IMAGE_NAME:latest
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/silema-repo/$IMAGE_NAME:$GIT_TAG
