name: MongoDB Daily Backup

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  backup-database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout c贸digo
      uses: actions/checkout@v3
    
    - name: Instalar MongoDB Database Tools
      run: |
        wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.9.0.deb
        sudo dpkg -i mongodb-database-tools-ubuntu2004-x86_64-100.9.0.deb
        mongodump --version
        mongorestore --version
    
    - name: Crear backup de producci贸n
      env:
        MONGO_URI_PROD: ${{ secrets.MONGO_URI_PROD }}
      run: |
        echo "Iniciando backup de base de datos de producci贸n..."
        mongodump --uri="${MONGO_URI_PROD}" \
          --out=./backup \
          --gzip
        echo "Backup completado"
        echo "Contenido del backup:"
        ls -la ./backup/365equipo/
    
    - name: Restaurar en base de datos de test
      env:
        MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
      run: |
        echo "Restaurando backup en base de datos de test..."
        # El flag --drop elimina las colecciones existentes antes de restaurar
        mongorestore --uri="${MONGO_URI_TEST}" \
          --gzip \
          --dir=./backup/365equipo \
          --nsInclude="365equipo.*" \
          --nsFrom="365equipo.*" \
          --nsTo="365equipo_test.*" \
          --drop \
          --verbose
        echo "Restauraci贸n completada"
