name: MongoDB Daily Backup

on:
  schedule:
    # Ejecutar todos los días a las 23:30 (hora UTC)
    - cron: '30 22 * * *'  # Ajusta según tu zona horaria
  workflow_dispatch: # Permite ejecución manual

jobs:
  backup-database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    
    - name: Instalar MongoDB Tools
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-database-tools
    
    - name: Crear backup de producción
      env:
        MONGO_URI_PROD: ${{ secrets.MONGO_URI_PROD }}
      run: |
        echo "Iniciando backup de base de datos de producción..."
        mongodump --uri="${MONGO_URI_PROD}" \
          --out=./backup \
          --gzip
        echo "Backup completado"
    
    - name: Limpiar base de datos de test
      env:
        MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
      run: |
        echo "Limpiando base de datos de test..."
        # Crear script para eliminar la base de datos
        cat > drop_db.js << EOF
        db.dropDatabase()
        EOF
        
        mongosh "${MONGO_URI_TEST}" --file drop_db.js
    
    - name: Restaurar en base de datos de test
      env:
        MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
      run: |
        echo "Restaurando backup en base de datos de test..."
        mongorestore --uri="${MONGO_URI_TEST}" \
          --gzip \
          --dir=./backup/365equipo \
          --nsInclude="365equipo.*" \
          --nsFrom="365equipo.*" \
          --nsTo="365equipo_test.*" \
          --drop
        echo "Restauración completada"
    
    - name: Verificar restauración
      env:
        MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
      run: |
        echo "Verificando restauración..."
        mongosh "${MONGO_URI_TEST}" --eval "db.stats()"
