name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - test
      - "releases/*"

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
          use-caches: false
          args: --coverage-report-dir=coverage
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1819043438 }}
          QODANA_ENDPOINT: "https://qodana.cloud"
        timeout-minutes: 5
